deployment:
  tasks:
    - echo "🚀 Starting deployment..."
    - cd $HOME/repositories/eco-packaging-backend
    - git pull origin main
    - npm install --production
    - echo "✅ Dependencies installed"
    - pm2 start index.js --name eco-packaging-backend || pm2 restart eco-packaging-backend
